version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - mkdir build
  build:
    commands:
      - npm run build
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
artifacts:
  files:
    - build/server.js
